### ISSUE TITLE
Error when sign up as trainer

### ISSUE THREAD

**Issue by baijum** [anandology/broadgauge#31]
This is the traceback

```
0.0 (1): SELECT * FROM users WHERE email = 'guest@example.com'
Traceback (most recent call last):
  File "/home/baiju/wa/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/home/baiju/wa/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/baiju/wa/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/home/baiju/wa/broadgauge/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "/home/baiju/wa/broadgauge/broadgauge/webapp.py", line 138, in GET
    user.make_trainer()
  File "/home/baiju/wa/broadgauge/local/lib/python2.7/site-packages/web/utils.py", line 76, in __getattr__
    raise AttributeError, k
AttributeError: 'make_trainer'
```

**Comment by anandology** [comment]
This is happening when an already existing user tries to signup as trainer. Fixed.
